version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources

  promguard:
    build:
      context: ..
      dockerfile: Containerfile
      platforms:
        - "linux/amd64"
    container_name: promguard
    depends_on:
      - prometheus
    volumes:
      - ../src/promguard-config.yaml:/app/promguard-config.yaml
    command: /app/promguard --config /app/promguard-config.yaml

volumes:
  prometheus_data:
  grafana_data:

