name: Build container image with release tag

on:
  push:
    tags:
    - 'promguard-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Containerfile --tag ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/promwatch-}
    - name: Login to Registry
      run: docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Registry
      run: docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/promwatch-}

